### ISSUE TITLE
parser IDEVICEINFO: value error

### ISSUE THREAD

**Issue by Banaanhangwagen** [ydkhatri/mac_apt#20] opened 2019-07-23 09:59 UTC
When parsing `com.apple.iPod.plist` with IDEVICEINFO, the script stumbles upon a Region Code which is not defined.

In my case this is `ZD`.

The script errors and quits. 

This can be resolved by adding the line `"Unknown Country = "ZD"` in iDeviceInfo.py.
(After a fast Google, I didn't find any documentation about it to fill in the right country.)

**Comment by ydkhatri** [comment] 2019-07-24 12:37
Can you submit the offending file (com.apple.iPod.plist) and also a DEBUG log?

**Comment by Banaanhangwagen** [comment] 2019-07-24 14:56
Unfortunatly, I cannot give you a copy of the file.

This is what DEBUG log says:
```
2019-07-24 16:47:44|MAIN.HELPERS.MACINFO|DEBUG|Trying to open plist file : /Users/REDACTED/Library/Preferences/com.apple.iPod.plist
2019-07-24 16:47:44|MAIN.HELPERS.MACINFO|DEBUG|Trying to open file : /Users/REDACTED/Library/Preferences/com.apple.iPod.plist
2019-07-24 16:47:44|MAIN.HELPERS.MACINFO|DEBUG|Trying to read plist file : /Users/REDACTED/Library/Preferences/com.apple.iPod.plist
2019-07-24 16:47:44|MAIN|ERROR|An exception occurred while running plugin - IDEVICEINFO
Traceback (most recent call last):
  File "mac_apt.py", line 454, in <module>
    plugin.Plugin_Start(mac_info)
  File "C:\Users\REDACTED\Downloads\mac_apt-master\plugins\iDeviceInfo.py", line 191, in Plugin_Start
    deviceFinder(userDevicePath, user_name, devices, 0, mac_info)
  File "C:\Users\REDACTED\Downloads\mac_apt-master\plugins\iDeviceInfo.py", line 170, in deviceFinder
    deviceReader(singleDevice, userDevicePath, user_name, devices)
  File "C:\Users\REDACTED\Downloads\mac_apt-master\plugins\iDeviceInfo.py", line 126, in deviceReader
    parsedCode = str(Country(rawCode))
  File "C:\Program Files\Python37\lib\enum.py", line 307, in __call__
    return cls.__new__(cls, value)
  File "C:\Program Files\Python37\lib\enum.py", line 555, in __new__
    return cls._missing_(value)
  File "C:\Program Files\Python37\lib\enum.py", line 568, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'ZD' is not a valid Country
2019-07-24 16:47:44|MAIN|INFO|--------------------------------------------------
```

![image](https://user-images.githubusercontent.com/25983612/61804222-d4e73c80-ae33-11e9-882a-e8e22bd47660.png)

**Comment by ydkhatri** [comment] 2019-07-24 16:29
Thanks, it seems that there are quite a few outliers out there like `ZD` . I will fix the code so it isn't limited to the known types.

**Comment by ydkhatri** [comment] 2019-07-25 05:13
I've fixed it in code and checked it in here. It will be a short while before I put out a new release.
Let me know if this works for you now.

**Comment by Banaanhangwagen** [comment] 2019-07-25 06:12
It works now as expected. Thanks.

Btw, do you have an idea where the region codes come from?

**Comment by ydkhatri** [comment] 2019-07-25 07:34
It seems to be Apple's custom list, not the standard country codes everyone else uses. A few people have reverse mapped it based on data they saw. like here  
 [https://www.premiuminfo.org/know-iphone-origin-country/](https://www.premiuminfo.org/know-iphone-origin-country/)   

I am closing the bug now as the problem is resolved.

**Closed** 2019-07-25 07:34 UTC
Labels: bug
